// (c) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// (c) Copyright 2022-2025 Advanced Micro Devices, Inc. All rights reserved.
// 
// This file contains confidential and proprietary information
// of AMD and is protected under U.S. and international copyright
// and other intellectual property laws.
// 
// DISCLAIMER
// This disclaimer is not a license and does not grant any
// rights to the materials distributed herewith. Except as
// otherwise provided in a valid license issued to you by
// AMD, and to the maximum extent permitted by applicable
// law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
// WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
// AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
// BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
// INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
// (2) AMD shall not be liable (whether in contract or tort,
// including negligence, or under any other theory of
// liability) for any loss or damage of any kind or nature
// related to, arising under or in connection with these
// materials, including for any direct, or any indirect,
// special, incidental, or consequential loss or damage
// (including loss of data, profits, goodwill, or any type of
// loss or damage suffered as a result of any action brought
// by a third party) even if such damage or loss was
// reasonably foreseeable or AMD had been advised of the
// possibility of the same.
// 
// CRITICAL APPLICATIONS
// AMD products are not designed or intended to be fail-
// safe, or for use in any application requiring fail-safe
// performance, such as life-support or safety devices or
// systems, Class III medical devices, nuclear facilities,
// applications related to the deployment of airbags, or any
// other applications that could lead to death, personal
// injury, or severe property or environmental damage
// (individually and collectively, "Critical
// Applications"). Customer assumes the sole risk and
// liability of any use of AMD products in Critical
// Applications, subject only to applicable laws and
// regulations governing limitations on product liability.
// 
// THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
// PART OF THIS FILE AT ALL TIMES.
// 
// DO NOT MODIFY THIS FILE.


// IP VLNV: xilinx.com:ip:pcie_phy:1.0
// IP Revision: 24

`timescale 1ns/1ps

(* DowngradeIPIdentifiedWarnings = "yes" *)
module pcie_phy_0 (
  phy_refclk,
  phy_gtrefclk,
  phy_rst_n,
  phy_txdata,
  phy_txdatak,
  phy_txdata_valid,
  phy_txstart_block,
  phy_txsync_header,
  phy_rxp,
  phy_rxn,
  phy_txdetectrx,
  phy_txelecidle,
  phy_txcompliance,
  phy_rxpolarity,
  phy_powerdown,
  phy_rate,
  phy_txmargin,
  phy_txswing,
  phy_txdeemph,
  phy_txeq_ctrl,
  phy_txeq_preset,
  phy_txeq_coeff,
  phy_rxeq_ctrl,
  phy_rxeq_txpreset,
  as_mac_in_detect,
  as_cdr_hold_req,
  phy_coreclk,
  phy_userclk,
  phy_mcapclk,
  phy_pclk,
  phy_txp,
  phy_txn,
  phy_rxdata,
  phy_rxdatak,
  phy_rxdata_valid,
  phy_rxstart_block,
  phy_rxsync_header,
  phy_rxvalid,
  phy_phystatus,
  phy_phystatus_rst,
  phy_rxelecidle,
  phy_rxstatus,
  phy_txeq_fs,
  phy_txeq_lf,
  phy_txeq_new_coeff,
  phy_txeq_done,
  phy_rxeq_preset_sel,
  phy_rxeq_new_txcoeff,
  phy_rxeq_adapt_done,
  phy_rxeq_done,
  gt_gtpowergood
);

(* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME CLK.PHY_REF_CLK, FREQ_HZ 100000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, INSERT_VIP 0" *)
(* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 CLK.PHY_REF_CLK CLK" *)
input wire phy_refclk;
(* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME CLK.PHY_GTREFCLK, FREQ_HZ 100000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, INSERT_VIP 0" *)
(* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 CLK.PHY_GTREFCLK CLK" *)
input wire phy_gtrefclk;
(* X_INTERFACE_PARAMETER = "XIL_INTERFACENAME RST.PHY_RST_N, POLARITY ACTIVE_LOW, INSERT_VIP 0" *)
(* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 RST.PHY_RST_N RST" *)
input wire phy_rst_n;
input wire [63 : 0] phy_txdata;
input wire [1 : 0] phy_txdatak;
input wire [0 : 0] phy_txdata_valid;
input wire [0 : 0] phy_txstart_block;
input wire [1 : 0] phy_txsync_header;
(* X_INTERFACE_INFO = "xilinx.com:interface:pcie_7x_mgt:1.0 pcie_mgt rxn" *)
input wire [0 : 0] phy_rxp;
(* X_INTERFACE_INFO = "xilinx.com:interface:pcie_7x_mgt:1.0 pcie_mgt rxp" *)
input wire [0 : 0] phy_rxn;
input wire phy_txdetectrx;
input wire [0 : 0] phy_txelecidle;
input wire [0 : 0] phy_txcompliance;
input wire [0 : 0] phy_rxpolarity;
input wire [1 : 0] phy_powerdown;
input wire [1 : 0] phy_rate;
input wire [2 : 0] phy_txmargin;
input wire phy_txswing;
input wire phy_txdeemph;
input wire [1 : 0] phy_txeq_ctrl;
input wire [3 : 0] phy_txeq_preset;
input wire [5 : 0] phy_txeq_coeff;
input wire [1 : 0] phy_rxeq_ctrl;
input wire [3 : 0] phy_rxeq_txpreset;
input wire as_mac_in_detect;
input wire as_cdr_hold_req;
output wire phy_coreclk;
output wire phy_userclk;
output wire phy_mcapclk;
output wire phy_pclk;
(* X_INTERFACE_INFO = "xilinx.com:interface:pcie_7x_mgt:1.0 pcie_mgt txn" *)
output wire [0 : 0] phy_txp;
(* X_INTERFACE_INFO = "xilinx.com:interface:pcie_7x_mgt:1.0 pcie_mgt txp" *)
output wire [0 : 0] phy_txn;
output wire [63 : 0] phy_rxdata;
output wire [1 : 0] phy_rxdatak;
output wire [0 : 0] phy_rxdata_valid;
output wire [1 : 0] phy_rxstart_block;
output wire [1 : 0] phy_rxsync_header;
output wire [0 : 0] phy_rxvalid;
output wire [0 : 0] phy_phystatus;
output wire phy_phystatus_rst;
output wire [0 : 0] phy_rxelecidle;
output wire [2 : 0] phy_rxstatus;
output wire [5 : 0] phy_txeq_fs;
output wire [5 : 0] phy_txeq_lf;
output wire [17 : 0] phy_txeq_new_coeff;
output wire [0 : 0] phy_txeq_done;
output wire [0 : 0] phy_rxeq_preset_sel;
output wire [17 : 0] phy_rxeq_new_txcoeff;
output wire [0 : 0] phy_rxeq_adapt_done;
output wire [0 : 0] phy_rxeq_done;
output wire [0 : 0] gt_gtpowergood;

  pcie_phy_0_core_top #(
    .COMPONENT_NAME("pcie_phy_0"),
    .PHY_LANE(1),
    .PHY_MAX_SPEED(1),
    .PHY_REFCLK_FREQ(0),
    .PHY_USERCLK_FREQ(2),
    .PHY_CORECLK_FREQ(1),
    .PLL_TYPE("CPLL"),
    .PIPELINE_STAGES(0),
    .REFCLK1_LOCATION("Bank_224_MGTREFCLK0"),
    .PHY_ASYNC_EN("TRUE"),
    .TX_PRESET(4),
    .INS_LOSS_PROFILE("ADD-IN_CARD"),
    .GT_TYPE("GTY"),
    .FPGA_FAMILY("USM"),
    .SILICON_VER_STR("Production"),
    .PHY_DATA_WIDTH(64),
    .RX_DETECT(0),
    .ASPM("No_ASPM"),
    .FPGA_XCVR("Y"),
    .EXT_CH_GT_DRP("FALSE"),
    .SHARED_LOGIC(1),
    .GTWIZ_IN_CORE(1),
    .GTCOM_IN_CORE(2),
    .ULTRASCALE("FALSE"),
    .ULTRASCALE_PLUS("TRUE"),
    .VERSAL("FALSE")
  ) inst (
    .phy_refclk(phy_refclk),
    .phy_gtrefclk(phy_gtrefclk),
    .phy_rst_n(phy_rst_n),
    .phy_txdata(phy_txdata),
    .phy_txdatak(phy_txdatak),
    .phy_txdata_valid(phy_txdata_valid),
    .phy_txstart_block(phy_txstart_block),
    .phy_txsync_header(phy_txsync_header),
    .phy_rxp(phy_rxp),
    .phy_rxn(phy_rxn),
    .phy_txdetectrx(phy_txdetectrx),
    .phy_txelecidle(phy_txelecidle),
    .phy_txcompliance(phy_txcompliance),
    .phy_rxpolarity(phy_rxpolarity),
    .phy_powerdown(phy_powerdown),
    .phy_rate(phy_rate),
    .phy_txmargin(phy_txmargin),
    .phy_txswing(phy_txswing),
    .phy_txdeemph(phy_txdeemph),
    .phy_txeq_ctrl(phy_txeq_ctrl),
    .phy_txeq_preset(phy_txeq_preset),
    .phy_txeq_coeff(phy_txeq_coeff),
    .phy_rxeq_ctrl(phy_rxeq_ctrl),
    .phy_rxeq_txpreset(phy_rxeq_txpreset),
    .as_mac_in_L0(1'B0),
    .cfg_rx_pm_state(2'B0),
    .as_mac_in_detect(as_mac_in_detect),
    .as_cdr_hold_req(as_cdr_hold_req),
    .phy_coreclk(phy_coreclk),
    .phy_userclk(phy_userclk),
    .phy_mcapclk(phy_mcapclk),
    .phy_pclk(phy_pclk),
    .phy_txp(phy_txp),
    .phy_txn(phy_txn),
    .phy_rxdata(phy_rxdata),
    .phy_rxdatak(phy_rxdatak),
    .phy_rxdata_valid(phy_rxdata_valid),
    .phy_rxstart_block(phy_rxstart_block),
    .phy_rxsync_header(phy_rxsync_header),
    .phy_rxvalid(phy_rxvalid),
    .phy_phystatus(phy_phystatus),
    .phy_phystatus_rst(phy_phystatus_rst),
    .phy_rxelecidle(phy_rxelecidle),
    .phy_rxstatus(phy_rxstatus),
    .phy_txeq_fs(phy_txeq_fs),
    .phy_txeq_lf(phy_txeq_lf),
    .phy_txeq_new_coeff(phy_txeq_new_coeff),
    .phy_txeq_done(phy_txeq_done),
    .phy_rxeq_preset_sel(phy_rxeq_preset_sel),
    .phy_rxeq_new_txcoeff(phy_rxeq_new_txcoeff),
    .phy_rxeq_adapt_done(phy_rxeq_adapt_done),
    .phy_rxeq_done(phy_rxeq_done),
    .gt_drpaddr(10'B0),
    .gt_drpen(1'B0),
    .gt_drpdi(16'B0),
    .gt_drpwe(1'B0),
    .gt_drpdo(),
    .gt_drprdy(),
    .gt_gtpowergood(gt_gtpowergood),
    .ext_qpllxrefclk(),
    .ext_qpllxrate(),
    .ext_qpllxrcalenb(),
    .ext_qpll0pd(),
    .ext_qpll0reset(),
    .ext_qpll0lock_out(1'B0),
    .ext_qpll0outclk_out(1'B0),
    .ext_qpll0outrefclk_out(1'B0),
    .ext_qpll1pd(),
    .ext_qpll1reset(),
    .ext_qpll1lock_out(1'B0),
    .ext_qpll1outclk_out(1'B0),
    .ext_qpll1outrefclk_out(1'B0),
    .rxdlysresetdone_us_out(1'B0),
    .rxelecidle_us_out(1'B0),
    .rxoutclk_us_out(1'B0),
    .rxphaligndone_us_out(1'B0),
    .rxpmaresetdone_us_out(1'B0),
    .rxprbserr_us_out(1'B0),
    .rxprbslocked_us_out(1'B0),
    .rxprgdivresetdone_us_out(1'B0),
    .rxratedone_us_out(1'B0),
    .rxresetdone_us_out(1'B0),
    .rxsyncdone_us_out(1'B0),
    .rxvalid_us_out(1'B0),
    .txdlysresetdone_us_out(1'B0),
    .txoutclk_us_out(1'B0),
    .txphaligndone_us_out(1'B0),
    .txphinitdone_us_out(1'B0),
    .txpmaresetdone_us_out(1'B0),
    .txprgdivresetdone_us_out(1'B0),
    .txresetdone_us_out(1'B0),
    .txsyncout_us_out(1'B0),
    .txsyncdone_us_out(1'B0),
    .cplllock_us_out(1'B0),
    .eyescandataerror_us_out(1'B0),
    .gtpowergood_us_out(1'B0),
    .pcierategen3_us_out(1'B0),
    .pcierateidle_us_out(1'B0),
    .pciesynctxsyncdone_us_out(1'B0),
    .pcieusergen3rdy_us_out(1'B0),
    .pcieuserphystatusrst_us_out(1'B0),
    .pcieuserratestart_us_out(1'B0),
    .phystatus_us_out(1'B0),
    .rxbyteisaligned_us_out(1'B0),
    .rxbyterealign_us_out(1'B0),
    .rxcdrlock_us_out(1'B0),
    .rxcommadet_us_out(1'B0),
    .gthtxn_us_out(1'B0),
    .gthtxp_us_out(1'B0),
    .drprdy_us_out(1'B0),
    .pcierateqpllpd_us_out(2'B0),
    .pcierateqpllreset_us_out(2'B0),
    .rxclkcorcnt_us_out(2'B0),
    .bufgtce_us_out(3'B0),
    .bufgtcemask_us_out(3'B0),
    .bufgtreset_us_out(3'B0),
    .bufgtrstmask_us_out(3'B0),
    .rxbufstatus_us_out(3'B0),
    .rxstatus_us_out(3'B0),
    .rxctrl2_us_out(8'B0),
    .rxctrl3_us_out(8'B0),
    .bufgtdiv_us_out(9'B0),
    .pcsrsvdout_us_out(12'B0),
    .drpdo_us_out(16'B0),
    .rxctrl0_us_out(16'B0),
    .rxctrl1_us_out(16'B0),
    .dmonitorout_us_out(17'B0),
    .rxdata_us_out(128'B0),
    .gtwiz_reset_rx_done_us_in(),
    .gtwiz_reset_tx_done_us_in(),
    .gtwiz_userclk_rx_active_us_in(),
    .gtwiz_userclk_tx_active_us_in(),
    .gtwiz_userclk_tx_reset_us_in(),
    .cpllpd_us_in(),
    .rxdfeagchold_us_in(),
    .rxdfecfokhold_us_in(),
    .rxdfelfhold_us_in(),
    .rxdfekhhold_us_in(),
    .rxdfetap2hold_us_in(),
    .rxdfetap3hold_us_in(),
    .rxdfetap4hold_us_in(),
    .rxdfetap5hold_us_in(),
    .rxdfetap6hold_us_in(),
    .rxdfetap7hold_us_in(),
    .rxdfetap8hold_us_in(),
    .rxdfetap9hold_us_in(),
    .rxdfetap10hold_us_in(),
    .rxdfetap11hold_us_in(),
    .rxdfetap12hold_us_in(),
    .rxdfetap13hold_us_in(),
    .rxdfetap14hold_us_in(),
    .rxdfetap15hold_us_in(),
    .rxdfeuthold_us_in(),
    .rxdfevphold_us_in(),
    .rxoshold_us_in(),
    .rxlpmgchold_us_in(),
    .rxlpmhfhold_us_in(),
    .rxlpmlfhold_us_in(),
    .rxlpmoshold_us_in(),
    .cpllreset_us_in(),
    .dmonfiforeset_us_in(),
    .dmonitorclk_us_in(),
    .drpclk_us_in(),
    .drpen_us_in(),
    .drpwe_us_in(),
    .eyescanreset_us_in(),
    .gthrxn_us_in(),
    .gthrxp_us_in(),
    .gtrefclk0_us_in(),
    .gtrxreset_us_in(),
    .gttxreset_us_in(),
    .pcieeqrxeqadaptdone_us_in(),
    .pcierstidle_us_in(),
    .pciersttxsyncstart_us_in(),
    .pcieuserratedone_us_in(),
    .rx8b10ben_us_in(),
    .rxbufreset_us_in(),
    .rxcdrhold_us_in(),
    .rxcommadeten_us_in(),
    .rxlpmen_us_in(),
    .rxmcommaalignen_us_in(),
    .rxpcommaalignen_us_in(),
    .rxpolarity_us_in(),
    .rxprbscntreset_us_in(),
    .rxprogdivreset_us_in(),
    .rxratemode_us_in(),
    .rxslide_us_in(),
    .rxuserrdy_us_in(),
    .rxusrclk2_us_in(),
    .rxusrclk_us_in(),
    .tx8b10ben_us_in(),
    .txdeemph_us_in(),
    .txdetectrx_us_in(),
    .txdlybypass_us_in(),
    .txdlyen_us_in(),
    .txdlyhold_us_in(),
    .txdlyovrden_us_in(),
    .txdlysreset_us_in(),
    .txdlyupdown_us_in(),
    .txelecidle_us_in(),
    .txinhibit_us_in(),
    .txphalign_us_in(),
    .txphalignen_us_in(),
    .txphdlypd_us_in(),
    .txphdlyreset_us_in(),
    .txphdlytstclk_us_in(),
    .txphinit_us_in(),
    .txphovrden_us_in(),
    .txprbsforceerr_us_in(),
    .txprogdivreset_us_in(),
    .txswing_us_in(),
    .txsyncallin_us_in(),
    .txsyncin_us_in(),
    .txsyncmode_us_in(),
    .txuserrdy_us_in(),
    .txusrclk2_us_in(),
    .txusrclk_us_in(),
    .rxpd_us_in(),
    .txpd_us_in(),
    .loopback_us_in(),
    .rxrate_us_in(),
    .txrate_us_in(),
    .txmargin_us_in(),
    .txoutclksel_us_in(),
    .rxprbssel_us_in(),
    .txdiffctrl_us_in(),
    .txprbssel_us_in(),
    .txprecursor_us_in(),
    .txpostcursor_us_in(),
    .txmaincursor_us_in(),
    .txctrl2_us_in(),
    .drpaddr_us_in(),
    .drpdi_us_in(),
    .pcsrsvdin_us_in(),
    .txctrl0_us_in(),
    .txctrl1_us_in(),
    .txdata_us_in(),
    .qpll0clk_us_in(),
    .qpll0refclk_us_in(),
    .qpll1clk_us_in(),
    .qpll1refclk_us_in(),
    .gtrefclk01_us_in(),
    .qpll1pd_us_in(),
    .qpll1reset_us_in(),
    .qpll1lock_us_out(1'B0),
    .qpll1outclk_us_out(1'B0),
    .qpll1outrefclk_us_out(1'B0),
    .qpllrsvd2_us_in(),
    .qpllrsvd3_us_in(),
    .gtrefclk01_usp_in(),
    .gtrefclk00_usp_in(),
    .pcierateqpll0_usp_in(),
    .pcierateqpll1_usp_in(),
    .qpll0pd_usp_in(),
    .qpll0reset_usp_in(),
    .qpll1pd_usp_in(),
    .qpll1reset_usp_in(),
    .qpll0lock_usp_out(1'B0),
    .qpll0outclk_usp_out(1'B0),
    .qpll0outrefclk_usp_out(1'B0),
    .qpll1lock_usp_out(1'B0),
    .qpll1outclk_usp_out(1'B0),
    .qpll1outrefclk_usp_out(1'B0),
    .qpll0freqlock_usp_in(),
    .qpll1freqlock_usp_in(),
    .pcierateqpllpd_usp_out(2'B0),
    .pcierateqpllreset_usp_out(2'B0),
    .gtwiz_reset_rx_done_usp_in(),
    .gtwiz_reset_tx_done_usp_in(),
    .gtwiz_userclk_rx_active_usp_in(),
    .gtwiz_userclk_tx_active_usp_in(),
    .loopback_usp_in(),
    .rxpd_usp_in(),
    .rxprbssel_usp_in(),
    .rxrate_usp_in(),
    .txctrl0_usp_in(),
    .txctrl1_usp_in(),
    .txctrl2_usp_in(),
    .txdata_usp_in(),
    .txdeemph_usp_in(),
    .txdiffctrl_usp_in(),
    .txprbssel_usp_in(),
    .txprecursor_usp_in(),
    .txrate_usp_in(),
    .txmaincursor_usp_in(),
    .txmargin_usp_in(),
    .txoutclksel_usp_in(),
    .txpd_usp_in(),
    .txpostcursor_usp_in(),
    .cpllfreqlock_usp_in(),
    .rcalenb_usp_in(),
    .cpllpd_usp_in(),
    .cpllreset_usp_in(),
    .dmonfiforeset_usp_in(),
    .dmonitorclk_usp_in(),
    .eyescanreset_usp_in(),
    .gtrefclk0_usp_in(),
    .gtrxreset_usp_in(),
    .gttxreset_usp_in(),
    .txpisopd_usp_in(),
    .pcieeqrxeqadaptdone_usp_in(),
    .pcierstidle_usp_in(),
    .pciersttxsyncstart_usp_in(),
    .pcieuserratedone_usp_in(),
    .resetovrd_usp_in(),
    .rx8b10ben_usp_in(),
    .rxbufreset_usp_in(),
    .rxcdrfreqreset_usp_in(),
    .rxcdrhold_usp_in(),
    .rxcdrreset_usp_in(),
    .rxcommadeten_usp_in(),
    .rxdfeagchold_usp_in(),
    .rxdfecfokhold_usp_in(),
    .rxdfekhhold_usp_in(),
    .rxdfelfhold_usp_in(),
    .rxdfelpmreset_usp_in(),
    .rxdfetap10hold_usp_in(),
    .rxdfetap11hold_usp_in(),
    .rxdfetap12hold_usp_in(),
    .rxdfetap13hold_usp_in(),
    .rxdfetap14hold_usp_in(),
    .rxdfetap15hold_usp_in(),
    .rxdfetap2hold_usp_in(),
    .rxdfetap3hold_usp_in(),
    .rxdfetap4hold_usp_in(),
    .rxdfetap5hold_usp_in(),
    .rxdfetap6hold_usp_in(),
    .rxdfetap7hold_usp_in(),
    .rxdfetap8hold_usp_in(),
    .rxdfetap9hold_usp_in(),
    .rxdfeuthold_usp_in(),
    .rxdfevphold_usp_in(),
    .rxlpmen_usp_in(),
    .rxlpmgchold_usp_in(),
    .rxlpmhfhold_usp_in(),
    .rxlpmlfhold_usp_in(),
    .rxlpmoshold_usp_in(),
    .rxmcommaalignen_usp_in(),
    .rxoshold_usp_in(),
    .rxpcommaalignen_usp_in(),
    .rxpcsreset_usp_in(),
    .rxpmareset_usp_in(),
    .rxpolarity_usp_in(),
    .rxprbscntreset_usp_in(),
    .rxprogdivreset_usp_in(),
    .rxslide_usp_in(),
    .rxtermination_usp_in(),
    .rxuserrdy_usp_in(),
    .rxusrclk2_usp_in(),
    .rxusrclk_usp_in(),
    .tx8b10ben_usp_in(),
    .txdetectrx_usp_in(),
    .txdlybypass_usp_in(),
    .txdlyen_usp_in(),
    .txdlyhold_usp_in(),
    .txdlyovrden_usp_in(),
    .txdlysreset_usp_in(),
    .txdlyupdown_usp_in(),
    .txelecidle_usp_in(),
    .txpcsreset_usp_in(),
    .txphalign_usp_in(),
    .txphalignen_usp_in(),
    .txphdlypd_usp_in(),
    .txphdlyreset_usp_in(),
    .txphdlytstclk_usp_in(),
    .txphinit_usp_in(),
    .txphovrden_usp_in(),
    .rxratemode_usp_in(),
    .txpmareset_usp_in(),
    .txprbsforceerr_usp_in(),
    .txprogdivreset_usp_in(),
    .txpdelecidlemode_usp_in(),
    .txswing_usp_in(),
    .txsyncallin_usp_in(),
    .txsyncin_usp_in(),
    .txsyncmode_usp_in(),
    .txuserrdy_usp_in(),
    .txusrclk2_usp_in(),
    .txusrclk_usp_in(),
    .rxclkcorcnt_usp_out(2'B0),
    .bufgtcemask_usp_out(3'B0),
    .bufgtrstmask_usp_out(3'B0),
    .rxbufstatus_usp_out(3'B0),
    .rxstatus_usp_out(3'B0),
    .rxctrl2_usp_out(8'B0),
    .rxctrl3_usp_out(8'B0),
    .bufgtdiv_usp_out(9'B0),
    .dmonitorout_usp_out(16'B0),
    .rxctrl0_usp_out(16'B0),
    .rxctrl1_usp_out(16'B0),
    .rxdata_usp_out(128'B0),
    .bufgtreset_usp_out(1'B0),
    .bufgtce_usp_out(1'B0),
    .cplllock_usp_out(1'B0),
    .gtpowergood_usp_out(1'B0),
    .pcierategen3_usp_out(1'B0),
    .pcierateidle_usp_out(1'B0),
    .pciesynctxsyncdone_usp_out(1'B0),
    .pcieusergen3rdy_usp_out(1'B0),
    .pcieuserphystatusrst_usp_out(1'B0),
    .pcieuserratestart_usp_out(1'B0),
    .phystatus_usp_out(1'B0),
    .rxbyteisaligned_usp_out(1'B0),
    .rxbyterealign_usp_out(1'B0),
    .rxcdrlock_usp_out(1'B0),
    .rxcommadet_usp_out(1'B0),
    .rxphaligndone_usp_out(1'B0),
    .rxpmaresetdone_usp_out(1'B0),
    .rxdlysresetdone_usp_out(1'B0),
    .rxelecidle_usp_out(1'B0),
    .rxoutclk_usp_out(1'B0),
    .rxoutclkfabric_usp_out(1'B0),
    .rxoutclkpcs_usp_out(1'B0),
    .rxprbserr_usp_out(1'B0),
    .rxprbslocked_usp_out(1'B0),
    .rxratedone_usp_out(1'B0),
    .rxrecclkout_usp_out(1'B0),
    .rxresetdone_usp_out(1'B0),
    .rxsyncdone_usp_out(1'B0),
    .txdlysresetdone_usp_out(1'B0),
    .rxvalid_usp_out(1'B0),
    .txoutclk_usp_out(1'B0),
    .txoutclkfabric_usp_out(1'B0),
    .txoutclkpcs_usp_out(1'B0),
    .txphaligndone_usp_out(1'B0),
    .txphinitdone_usp_out(1'B0),
    .txpmaresetdone_usp_out(1'B0),
    .txprgdivresetdone_usp_out(1'B0),
    .txresetdone_usp_out(1'B0),
    .txsyncdone_usp_out(1'B0),
    .txsyncout_usp_out(1'B0),
    .ext_phy_clk_bufg_gt_ce(),
    .ext_phy_clk_bufg_gt_reset(),
    .ext_phy_clk_rst_idle(),
    .ext_phy_clk_txoutclk(),
    .ext_phy_clk_bufgtcemask(),
    .ext_phy_clk_gt_bufgtrstmask(),
    .ext_phy_clk_bufgtdiv(),
    .ext_phy_clk_pclk2_gt(1'B0),
    .ext_phy_clk_int_clock(1'B0),
    .ext_phy_clk_pclk(1'B0),
    .ext_phy_clk_phy_pclk2(1'B0),
    .ext_phy_clk_phy_coreclk(1'B0),
    .ext_phy_clk_phy_userclk(1'B0),
    .ext_phy_clk_phy_mcapclk(1'B0),
    .drpdo_usp_out(16'B0),
    .drprdy_usp_out(1'B0),
    .drpclk_usp_in(),
    .drpaddr_usp_in(),
    .drpen_usp_in(),
    .drpdi_usp_in(),
    .drpwe_usp_in(),
    .drprst_usp_in()
  );
endmodule
